from __future__ import annotations

from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one replacement, got {count}")
    p.write_text(text.replace(old, new), encoding="utf-8")


path = "arvectum_data/engine/html_records.py"
replace_once(
    path,
    '''_MACHINE_DATA_KEYS = {"data-coupon-id", "data-promocode", "data-promo-code"}\n_SEMANTIC_TOKENS = {''',
    '''_MACHINE_DATA_KEYS = {"data-coupon-id", "data-promocode", "data-promo-code"}\n_CONTROL_ACTION_RE = re.compile(\n    r"(?:добавить|предложить|разместить|submit|add|share)\\s+(?:свой\\s+)?"\n    r"(?:промокод\\w*|купон\\w*|скидк\\w*|offer\\w*|promo\\w*|coupon\\w*|deal\\w*)",\n    re.IGNORECASE,\n)\n_CONTACT_TEXT_RE = re.compile(\n    r"(?:@[A-Za-z0-9_.-]+|[A-Za-z0-9_.+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|"\n    r"[A-Za-z0-9.-]+\\.[A-Za-z]{2,})$",\n    re.IGNORECASE,\n)\n_SEMANTIC_TOKENS = {''',
)
replace_once(
    path,
    '''def _is_action_node(node: _Node) -> bool:\n    if node.tag not in {"a", "button"}:\n        return False\n    href = node.attrs.get("href", "")\n    if "offer_id=" in href:\n        return True\n    text = node.text()\n    if _ACTION_RE.search(text):\n        return not _is_navigation_node(node)\n    # Some production sites label the actionable element with the benefit itself\n    # rather than an imperative verb. Keep this generic and bounded, and do not\n    # promote global navigation/chrome into business records.\n    return bool(\n        text\n        and len(text) <= 280\n        and not _is_navigation_node(node)\n        and _OFFER_SIGNAL_RE.search(text)\n        and (node.tag == "button" or bool(href))\n    )\n\n\ndef _is_offer_id_action(node: _Node) -> bool:\n    return node.tag == "a" and "offer_id=" in node.attrs.get("href", "")\n''',
    '''def _is_action_node(node: _Node) -> bool:\n    if node.tag not in {"a", "button"}:\n        return False\n    href = node.attrs.get("href", "")\n    if "offer_id=" in href:\n        return True\n    text = node.text()\n    if _is_navigation_node(node) or _CONTROL_ACTION_RE.search(text):\n        return False\n    if node.tag == "a" and href.casefold().startswith(("javascript:", "mailto:", "tel:")):\n        return False\n    if _CONTACT_TEXT_RE.fullmatch(text):\n        return False\n    if _ACTION_RE.search(text):\n        return True\n    # Some production sites label the actionable element with the benefit itself\n    # rather than an imperative verb. Keep this generic and bounded, and do not\n    # promote global navigation/chrome into business records.\n    return bool(\n        text\n        and len(text) <= 280\n        and _OFFER_SIGNAL_RE.search(text)\n        and (node.tag == "button" or bool(href))\n    )\n\n\ndef _offer_id_value(node: _Node) -> str | None:\n    if node.tag != "a":\n        return None\n    match = re.search(r"(?:[?&])offer_id=([^&#]+)", node.attrs.get("href", ""), re.IGNORECASE)\n    return match.group(1) if match else None\n\n\ndef _is_offer_id_action(node: _Node) -> bool:\n    return _offer_id_value(node) is not None\n''',
)
replace_once(
    path,
    '''def _is_benefit_heading(node: _Node) -> bool:\n    return node.tag in {"h2", "h3", "h4"} and bool(_BENEFIT_HEADING_RE.search(node.text()))\n\n\ndef _count_descendants(node: _Node, predicate) -> int:\n    return sum(1 for current in node.walk() if predicate(current))\n\n\ndef _is_explicit_action_node(node: _Node) -> bool:\n    if node.tag not in {"a", "button"}:\n        return False\n    href = node.attrs.get("href", "")\n    if "offer_id=" in href:\n        return True\n    return bool(_ACTION_RE.search(node.text())) and not _is_navigation_node(node)\n\n\ndef _is_benefit_action_node(node: _Node) -> bool:\n    return _is_action_node(node) and not _is_explicit_action_node(node)\n\n\ndef _contains_multiple_offer_units(node: _Node) -> bool:\n    """Return True when one container visibly spans more than one offer unit.\n\n    A single offer commonly exposes several *different* signals at once (for\n    example one heading + one reveal action + one machine coupon id), so summing\n    all anchors would split valid cards. Explicit actions and benefit-labelled\n    links are counted separately: one of each can belong to the same card, while\n    repetition within either category marks a list/wrapper.\n    """\n\n    return any(\n        count > 1\n        for count in (\n            _count_descendants(node, _has_machine_marker),\n            _count_descendants(node, _is_offer_id_action),\n            _count_descendants(node, _is_explicit_action_node),\n            _count_descendants(node, _is_benefit_action_node),\n            _count_descendants(node, _is_benefit_heading),\n        )\n    )\n''',
    '''def _is_benefit_heading(node: _Node) -> bool:\n    return (\n        node.tag in {"h2", "h3", "h4"}\n        and not _is_navigation_node(node)\n        and not _CONTROL_ACTION_RE.search(node.text())\n        and bool(_BENEFIT_HEADING_RE.search(node.text()))\n    )\n\n\ndef _count_descendants(node: _Node, predicate) -> int:\n    return sum(1 for current in node.walk() if predicate(current))\n\n\ndef _unique_coupon_identity_count(node: _Node) -> int:\n    values = {\n        _compact(current.attrs.get("data-coupon-id", ""))\n        for current in node.walk()\n        if current.attrs.get("data-coupon-id")\n    }\n    if values:\n        return len(values)\n    # Promo-code-only markup is not guaranteed to be a unique business identity:\n    # two sibling offers may legitimately share one code, so keep node counting\n    # for weaker machine markers instead of accidentally merging those offers.\n    return _count_descendants(node, _has_machine_marker)\n\n\ndef _unique_offer_id_count(node: _Node) -> int:\n    return len({value for current in node.walk() if (value := _offer_id_value(current))})\n\n\ndef _is_explicit_action_node(node: _Node) -> bool:\n    if node.tag not in {"a", "button"} or _is_offer_id_action(node):\n        return False\n    return (\n        bool(_ACTION_RE.search(node.text()))\n        and not _is_navigation_node(node)\n        and not _CONTROL_ACTION_RE.search(node.text())\n    )\n\n\ndef _is_benefit_action_node(node: _Node) -> bool:\n    return (\n        _is_action_node(node)\n        and not _is_offer_id_action(node)\n        and not _is_explicit_action_node(node)\n    )\n\n\ndef _contains_multiple_offer_units(node: _Node) -> bool:\n    """Return True when one container visibly spans more than one offer unit.\n\n    Repeated DOM representations of the same strong identity are one offer: a\n    card may copy ``data-coupon-id`` onto both its wrapper and reveal button, or\n    repeat the same ``offer_id`` in nested links. Distinct identity values still\n    stop boundary growth. We keep weaker action/heading signals conservative and\n    count their DOM occurrences because they are not guaranteed unique.\n    """\n\n    return any(\n        count > 1\n        for count in (\n            _unique_coupon_identity_count(node),\n            _unique_offer_id_count(node),\n            _count_descendants(node, _is_explicit_action_node),\n            _count_descendants(node, _is_benefit_action_node),\n            _count_descendants(node, _is_benefit_heading),\n        )\n    )\n''',
)
replace_once(
    path,
    '''        groups: tuple[tuple[int, str, float, Sequence[_Node]], ...] = (\n            # Exact-card arbitration: offer-id is strongest; a linked benefit\n            # heading carries the canonical target link; an explicit action keeps\n            # its href while still exposing machine data from the card.\n            (9, "action", 0.99, [node for node in nodes if _is_offer_id_action(node)]),\n            (8, "heading", 0.97, [node for node in nodes if _is_linked_benefit_heading(node)]),\n            (7, "action", 0.96, [\n                node for node in nodes if _is_action_node(node) and not _is_offer_id_action(node)\n            ]),\n            (6, "machine", 0.99, [node for node in nodes if _has_machine_marker(node)]),\n            (5, "heading", 0.94, [\n                node for node in nodes if _is_benefit_heading(node) and not _is_linked_benefit_heading(node)\n            ]),\n        )''',
    '''        groups: tuple[tuple[int, str, float, Sequence[_Node]], ...] = (\n            # Exact-card arbitration: offer-id remains strongest. A semantic\n            # benefit heading outranks a generic action or machine marker because\n            # it carries the business title while the enclosing card still keeps\n            # machine/action evidence available to candidate providers.\n            (10, "action", 0.99, [node for node in nodes if _is_offer_id_action(node)]),\n            (9, "heading", 0.97, [node for node in nodes if _is_linked_benefit_heading(node)]),\n            (8, "heading", 0.95, [\n                node for node in nodes if _is_benefit_heading(node) and not _is_linked_benefit_heading(node)\n            ]),\n            (7, "action", 0.96, [\n                node for node in nodes if _is_action_node(node) and not _is_offer_id_action(node)\n            ]),\n            (6, "machine", 0.99, [node for node in nodes if _has_machine_marker(node)]),\n        )''',
)

test_path = Path("tests/dp_engine/test_semantic_html_records.py")
test_text = test_path.read_text(encoding="utf-8")
marker = "def test_repeated_same_coupon_identity_collapses_to_one_semantic_card() -> None:"
if marker not in test_text:
    test_text += '''\n\n\ndef test_repeated_same_coupon_identity_collapses_to_one_semantic_card() -> None:\n    result = _records(\n        """\n        <div class='offer' data-coupon-id='42'>\n          <h3>Скидка 20% на заказ</h3>\n          <button data-coupon-id='42'>Показать промокод</button>\n        </div>\n        """\n    )\n    assert len(result.records) == 1\n    attrs = result.records[0].asset.attributes\n    assert attrs["record_anchor_kind"] == "heading"\n    assert attrs["record_heading"] == "Скидка 20% на заказ"\n    assert attrs["record_data"]["data-coupon-id"] == "42"\n\n\ndef test_distinct_coupon_identities_remain_separate_records() -> None:\n    result = _records(\n        """\n        <section>\n          <div data-coupon-id='42'><h3>Скидка 20% на Alpha</h3><button data-coupon-id='42'>Показать промокод</button></div>\n          <div data-coupon-id='43'><h3>Скидка 30% на Beta</h3><button data-coupon-id='43'>Показать промокод</button></div>\n        </section>\n        """\n    )\n    assert len(result.records) == 2\n    assert [record.asset.attributes["record_data"]["data-coupon-id"] for record in result.records] == ["42", "43"]\n\n\ndef test_repeated_same_offer_id_does_not_split_one_card() -> None:\n    result = _records(\n        """\n        <div class='offer'>\n          <a href='/?offer_id=77#offer-77'>Скидка на заказ</a>\n          <a href='/?offer_id=77#offer-77'>Показать промокод</a>\n        </div>\n        """\n    )\n    assert len(result.records) == 1\n    assert result.records[0].asset.attributes["record_action_href"] == "/?offer_id=77#offer-77"\n\n\ndef test_contact_pseudo_links_and_footer_headings_are_not_offer_records() -> None:\n    result = _records(\n        """\n        <main>\n          <a href='mailto:promokodik@example.com'>promokodik@example.com</a>\n          <a href='javascript:void(0)'>Промокодов 18</a>\n          <h3>Добавить свой промокод</h3>\n          <div><h3>Скидка 25% на заказ</h3></div>\n        </main>\n        <footer><h3>Скидки и предложения</h3></footer>\n        """\n    )\n    assert len(result.records) == 1\n    assert result.records[0].asset.attributes["record_heading"] == "Скидка 25% на заказ"\n'''
    test_path.write_text(test_text, encoding="utf-8")
