from __future__ import annotations

from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one replacement, got {count}")
    p.write_text(text.replace(old, new), encoding="utf-8")


path = "arvectum_data/engine/html_records.py"
replace_once(
    path,
    '''def _count_descendants(node: _Node, predicate) -> int:\n    return sum(1 for current in node.walk() if predicate(current))\n\n\ndef _bounded_card(anchor: _Node, *, anchor_kind: str, max_chars: int = 2200) -> _Node:\n    """Resolve one strong offer anchor to a bounded record container.\n\n    We never cross an ancestor that contains multiple anchors of the same strong\n    kind. This prevents a page/list wrapper from becoming one record and keeps\n    navigation/promotional index noise out of the record set.\n    """\n\n    if anchor_kind == "heading":\n        predicate = _is_benefit_heading\n    elif anchor_kind == "machine":\n        predicate = _has_machine_marker\n    else:\n        predicate = _is_action_node\n    fallback = anchor\n    current = anchor.parent\n    while current is not None and current.tag not in {"document", "html", "body"}:\n        text = current.text()\n        if not text or len(text) > max_chars:\n            current = current.parent\n            continue\n        if _count_descendants(current, predicate) > 1:\n            break\n        fallback = current\n        if current.tag in {"article", "li"}:\n            return current\n        current = current.parent\n    return fallback\n''',
    '''def _count_descendants(node: _Node, predicate) -> int:\n    return sum(1 for current in node.walk() if predicate(current))\n\n\ndef _contains_multiple_offer_units(node: _Node) -> bool:\n    """Return True when one container visibly spans more than one offer unit.\n\n    A single offer commonly exposes several *different* signals at once (for\n    example one heading + one reveal action + one machine coupon id), so summing\n    all anchors would split valid cards. Lists/wrappers, however, repeat at least\n    one strong signal type across siblings. Bounding against every strong type\n    prevents an action-only branch from climbing across several heading cards,\n    and vice versa, without relying on host-specific selectors or vocabulary.\n    """\n\n    return any(\n        count > 1\n        for count in (\n            _count_descendants(node, _has_machine_marker),\n            _count_descendants(node, _is_offer_id_action),\n            _count_descendants(node, _is_action_node),\n            _count_descendants(node, _is_benefit_heading),\n        )\n    )\n\n\ndef _bounded_card(anchor: _Node, *, anchor_kind: str, max_chars: int = 2200) -> _Node:\n    """Resolve one strong offer anchor to a cross-signal-bounded card.\n\n    The boundary may contain one machine marker, one action and one benefit\n    heading for the same offer, but it never crosses an ancestor that repeats any\n    strong signal type. This makes mixed-layout pages tree-safe: a lone action\n    cannot absorb several heading-only siblings, and a lone machine marker cannot\n    absorb a list of actionable offers.\n    """\n\n    del anchor_kind\n    fallback = anchor\n    current = anchor.parent\n    while current is not None and current.tag not in {"document", "html", "body"}:\n        text = current.text()\n        if not text or len(text) > max_chars:\n            current = current.parent\n            continue\n        if _contains_multiple_offer_units(current):\n            break\n        fallback = current\n        if current.tag in {"article", "li"}:\n            return current\n        current = current.parent\n    return fallback\n''',
)


test_path = Path("tests/dp_engine/test_semantic_html_records.py")
test_text = test_path.read_text(encoding="utf-8")
marker = "def test_cross_signal_wrapper_does_not_absorb_heading_siblings() -> None:"
if marker not in test_text:
    test_text += '''\n\n\ndef test_cross_signal_wrapper_does_not_absorb_heading_siblings() -> None:\n    result = _records(\n        """\n        <section class='offer-list'>\n          <div class='entry'><a href='/one'><h3>Промокод Alpha 10%</h3></a></div>\n          <div class='entry'><a href='/two'><h3>Скидка Beta 20%</h3></a></div>\n          <div class='entry'><button>Открыть промокод</button></div>\n        </section>\n        """\n    )\n    assert len(result.records) == 3\n    assert all(record.asset.attributes["record_tag"] != "section" for record in result.records)\n\n\ndef test_cross_signal_boundary_keeps_one_mixed_offer_together() -> None:\n    result = _records(\n        """\n        <div class='entry'>\n          <a href='/shop'><h3>Скидка 25% в Alpha</h3></a>\n          <div><span data-coupon-id='77'></span><button>Показать промокод</button></div>\n        </div>\n        """\n    )\n    assert len(result.records) == 1\n    attrs = result.records[0].asset.attributes\n    assert attrs["record_tag"] == "div"\n    assert attrs["record_heading"] == "Скидка 25% в Alpha"\n    assert attrs["record_data"]["data-coupon-id"] == "77"\n\n\ndef test_machine_offer_cannot_climb_over_multiple_action_siblings() -> None:\n    result = _records(\n        """\n        <main>\n          <div class='entry'><span data-coupon-id='1'></span><a href='/one'>Получить промокод</a></div>\n          <div class='entry'><a href='/two'>Открыть промокод</a></div>\n        </main>\n        """\n    )\n    assert len(result.records) == 2\n    assert [record.asset.attributes["record_href"] for record in result.records] == ["/one", "/two"]\n'''
    test_path.write_text(test_text, encoding="utf-8")
